baseurl = "https://jspolice.com/"
languageCode = "en-us"
title = "JSPolice"
googleAnalytics = "UA-80126273-1"
disqusShortname = "jspolice"
copyright = "Copyright *Petar Slovic*"

[params]
  name = "JSPolice"
  description = "JS Police desc?"
  title = "Review & Contributions"
  tagline = "Let's improve JS Open Source Projects."
  enableRSS = true
  comment = true

[social]
  twitter  = "https://twitter.com/JSPoliceReviews"
  email  = "petar@jspolice.com"
  github = "https://www.github.com/jspolice"
  youtube = "https://www.youtube.com/channel/UCPd7dPOKxlj6qMBiAsbvMKQ"
  mail = "petar@petarslovic.com"
